version: '3.7'

services:
  web:
    build: .
    command: gunicorn kodeland_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kodeland
      - POSTGRES_PASSWORD=kodeland
      - POSTGRES_DB=kodeland_blog
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 5000:80
    depends_on:
      - web
      
volumes:
  postgres_data:
  static_volume:
  media_volume: